### PR TITLE
Merged done moving to next 

### PR DESCRIPTION
**Pull request by deep-69bits**
image

### CODE REVIEW

**Comment by pranavgade20** [comment]
is this a solution to https://github.com/pranavgade20/practice-git/blob/master/SQUASH_AND_MERGE.md ? please be clearer about that in the title/description if you can :)

If you are indeed solving SQUASH_AND_MERGE, you should probably be on a branch called 'squashing'

Feel free to reopen if this isn't a solution to SQUASH_AND_MERGE, but you need to create a separate branch if it is

**Comment by deep-69bits** [comment]
sir this was 3rd task where we have to create 3 branches and merge the ihave 
image

**Comment by deep-69bits** [comment]
SIR, IT WAS SOLUTION OF 3RD TASK WHERE WE HAVE TO CREATE 3 BRANCHES BRANCHING ... ETC THIS IS NOT FAIR SIR U HAVENT ASSIGNED ME POINT BECAUSE OF THIS  I AM ON 39TH  POSITION  AND I HAVE DONE IT BEFORE MANY OF THEM
some people asked for (to be assigned projects) before completing (a must to tasks)  is it is fair ???
I think I should not participate  in this event further and more events like this
THANKYOU.

**Comment by pranavgade20** [comment]
You simply need to create one new branch and one new pr before I accept this. You don't need to ask to be assigned any tasks in this repo, so I'm looking forward to more contributions from you :)

Participation is up to you, but we strongly recommend you continue, so that you can learn more about working with git and the open source community. Finally, don't worry about the leaderboard because it's kindof buggy and not the final version. When the event ends, we will go through all contributions and tally up the correct points for everyone.

**Pull request closed without merging**
